In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression#binary classification tasks, where the goal is to 
#predict the probability that an instance belongs to a particular class (0 or 1, yes or no, etc.)
from sklearn.decomposition import PCA
#setting n_components=4 in PCA can be a useful approach for dimensionality reduction, 
#capturing variance, simplifying data, improving performance, and data visualization.
import pickle
import matplotlib.pyplot as plt

def selectpca(X_train,X_test,n):
        pca = PCA(n_components=n)
        pca = PCA(n_components = 2)
        X_train = pca.fit_transform(X_train)
        X_test = pca.transform(X_test)
        explained_variance = pca.explained_variance_ratio_
        return X_train, X_test, explained_variance
#def split_scalar(indep_X,dep_Y): #train test split preprocess
def split_scalar(X,y, test_size=0.2, random_state=0):         
        #X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
def cm_prediction(classifier, X_test, y_test):#predict method of the classifier object to make predictions on the X_test data and 
    #stores the predicted labels in the y_pred variable.

     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)     # classification algorithm ML using confusion matrix
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )        #using accuracy
        
     report=classification_report(y_test, y_pred)     #using report
     return  classifier,Accuracy,report,y_pred,cm
def logistic(X_train,y_train):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    
    
def svm_linear(X_train,y_train):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    
            
    
def svm_NL(X_train,y_train):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    

def Navie(X_train,y_train):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
            
    
    
def knn(X_train,y_train):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    
def Decision(X_train,y_train):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    


def random(X_train,y_train):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,y_pred,cm=cm_prediction(classifier,X_test,y_test)   #cm_prediction called here
        return  classifier,Accuracy,report,y_pred,cm 
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [10]:
dataset = pd.read_csv('Wine.csv')
X = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, 13].values

In [11]:
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [12]:
X_train = np.array([[1, 2], [3, 4], [5, 6]])
X_test = np.array([[7, 8], [9, 10], [11, 12]])
n = 2

best = selectpca(X_train,X_test,n)

In [13]:
best

(array([[-2.82842712,  0.        ],
        [ 0.        ,  0.        ],
        [ 2.82842712,  0.        ]]),
 array([[5.65685425e+00, 4.44089210e-16],
        [8.48528137e+00, 6.66133815e-16],
        [1.13137085e+01, 8.88178420e-16]]),
 array([1., 0.]))

In [14]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [15]:
X_train, X_test, y_train, y_test=split_scalar(X,y, test_size=0.2, random_state=0)   
    
        
classifier,Accuracy,report,y_pred,cm=logistic(X_train,y_train)
acclog.append(Accuracy)

classifier,Accuracy,report,y_pred,cm=svm_linear(X_train,y_train)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,y_pred,cm=svm_NL(X_train,y_train)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,y_pred,cm=knn(X_train,y_train)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,y_pred,cm=Navie(X_train,y_train)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,y_pred,cm=Decision(X_train,y_train)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,y_pred,cm=random(X_train,y_train)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7180\119404528.py:119: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][idex]=acclog[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7180\119404528.py:120: FutureWarning: C

In [16]:
result

Logistic SVMl SVMnl       KNN     Navie  Decision    Random
PCA      1.0  1.0   1.0  0.972222  0.916667  0.916667  0.972222